general_q = [{"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Dihydrogen Monoxide was banned due to health risks"
                                  "after being discovered in 1983 inside swimming pools and drinking water.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "In 2010, Twitter and the United States Library of "
                                  "Congress partnered together to archive every tweet by American citizens.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Romanian belongs to the Romance language family,"
                                  " shared with French, Spanish, Portuguese and Italian. ",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "It is automatically considered entrapment"
                                  " in the United States if the police sell you "
                                  "illegal substances without revealing themselves.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Scotland voted to become an independent country "
                                  "during the referendum from September 2014.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Video streaming website YouTube was purchased in it's "
                                  "entirety by Facebook for US$1.65 billion in stock.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "A scientific study on peanuts in bars found traces"
                                  " of over 100 unique specimens of urine.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "The color orange is named after the fruit.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Pluto is a planet.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "There are 86400 seconds in a day.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "The average woman is 5 inches 13 centimeters shorter than the average man.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "Francis Bacon died from a fatal case of pneumonia "
                                  "while he was attempting to preserve meat by stuffing a chicken with snow.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "Albert Einstein had trouble with mathematics when he was in school.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "An eggplant is a vegetable.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "Sitting for more than three hours a day can cut "
                                  "two years off a person's life expectancy.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                      "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
                      "correct_answer": "False", "incorrect_answers": ["True"]}]
computers_q = [{"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "Linux was first created as an alternative to Windows XP.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "The programming language Python is based off a modified version of JavaScript.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "Ada Lovelace is often considered the first computer programmer.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "In most programming languages, the operator ++ "
                          "is equivalent to the statement +=.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
              "question": "The NVidia GTX 1080 gets its name because "
                          "it can only render at a 1920x1080 screen resolution.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "All program codes have to be compiled into an executable file in order to be run. "
                          "This file can then be executed on any machine.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "The very first recorded computer bug was a moth found inside a "
                          "Harvard Mark II computer.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "The common software-programming acronym I18N comes from the term Interlocalization",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "A Boolean value of &quot;0&quot; represents which of these words?",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "To bypass US Munitions Export Laws, "
                          "the creator of the PGP published all the source code in book form. ",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
              "question": "Linus Sebastian is the creator of the Linux kernel, "
                          "which went on to be used in Linux, Android, and Chrome OS.",
              "correct_answer": "False", "incorrect_answers": ["True"]}]

music_q = [{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "The alternative rock band, They Might Be Giants, released their album Flood in 1990. ",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "Scatman John&#039;s real name was John Paul Larkin.", "correct_answer": "True",
          "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                            "question": "Lead Singer Rivers Cuomo of American rock band "
                                                        "Weezer attended Harvard.",
                                            "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "Korean girl group, TWICE, consists of 9 members", "correct_answer": "True",
          "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                            "question": "Michael Jackson wrote The Simpsons song 'Do the Bartman'.",
                                            "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "Stevie Wonder&#039;s real name is Stevland Hardaway Morris.", "correct_answer": "True",
          "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                            "question": "The 2011 movie 'The Adventures of Tintin' "
                                                        "was directed by Steven Spielberg.",
                                            "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "Muse is a British (English) rock band", "correct_answer": "True",
          "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                            "question": "In 1993, Prince changed his name to an unpronounceable symbol"
                                                        " because he was unhappy with his contract with Warner Bros.",
                                            "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "A Saxophone is a brass instrument.", "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "The music group Daft Punk got their name from a negative review they recieved.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "Daft Punk originated in France.", "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "3 members of 2 Live Crew were arrested for playing songs from their album,"
                      " As Nasty As They Wanna Be, live.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "&quot;Neutral Milk Hotel&quot; is a real band.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "&quot;Twenty One Pilots&quot; made the song &quot;The Motion&quot; featuring Sampha.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap Song in 2007.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "Ashley Frangipane performs under the stage name Halsey.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "A Facebook campaign placed Rage Against The Machine Killing in the Name Of "
                      "as the UK Christmas Number 1 in 2009.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin Broadus, Jr.&#039;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "The cover of The Beatles album &quot;Abbey Road&quot; "
                      "featured a Volkswagen Beetle in the background.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
          "question": "EDM label Monstercat signs tracks instead of artists.", "correct_answer": "True",
          "incorrect_answers": ["False"]}]
